global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'permitguard-api'
    scrape_interval: 15s
    metrics_path: /metrics
    authorization:
      type: Bearer
      credentials: 186dca44ef618bd69eb96495311cb91f53c091e0772402bc71c6904d254d7ddf
    static_configs:
      - targets: ['codechecker.railway.internal:8080']
        labels:
          service: permitguard-api

  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE